cloud_controller/apps_domain: apps.lab.winterfell.live
cloud_controller/system_domain: sys.lab.winterfell.live
router/static_ips: 192.168.7.31
control/static_ips: 192.168.7.32
mysql_monitor/recipient_email: dpfeffer@pivotal.io
credhub_key_encryption_passwords_0/key: ((properties_credhub_key_encryption_passwords_0_key_secret))
credhub_key_encryption_passwords_0/name: credhub-encryption-key
credhub_key_encryption_passwords_0/primary: true
networking_poe_ssl_certs_0/name: pas-cert
networking_poe_ssl_certs_0/certificate: ((cf/networking_poe_ssl_certs_0_certificate.certificate))
networking_poe_ssl_certs_0/privatekey: ((cf/networking_poe_ssl_certs_0_certificate.private_key))
uaa/service_provider_key_credentials/certificate: ((cf/uaa_service_provider_key_credentials.certificate))
uaa/service_provider_key_credentials/privatekey: ((cf/uaa_service_provider_key_credentials.private_key))
uaa/ldap/url: ldap://ldap.jumpcloud.com:389
uaa/ldap/credentials_identity: uid=servicebind,ou=Users,o=5c390cd9c556772e64d4fbb5,dc=jumpcloud,dc=com
uaa/ldap/credentials_password: ((uaa_ldap_password))
uaa/ldap/search_base: ou=Users,o=5c390cd9c556772e64d4fbb5,dc=jumpcloud,dc=com
uaa/ldap/search_filter: (&(objectClass=inetOrgPerson)(uid={0}))
uaa/ldap/group_search_base: ou=Users,o=5c390cd9c556772e64d4fbb5,dc=jumpcloud,dc=com
uaa/ldap/group_search_filter: member={0}
uaa/ldap/first_name_attribute: givenName
uaa/ldap/last_name_attribute: sn
uaa/ldap/mail_attribute_name: mail
uaa/ldap/external_groups_whitelist: pks_*
uaa/ldap/ldap_referrals: 

network_name: deployment

security_acknowledgement: X
singleton_availability_zone: az1
ha_proxy/skip_cert_verify: true
