cloud_controller/apps_domain: apps.lab.winterfell.live
cloud_controller/system_domain: sys.lab.winterfell.live
router/static_ips: 192.168.7.32
control/static_ips: 192.168.7.31

mysql_monitor/recipient_email: dpfeffer@pivotal.io

properties_credhub_key_encryption_passwords_0_key.secret: ((properties_credhub_key_encryption_passwords_0_key_secret))

uaa/ldap/url: ldap://ldap.jumpcloud.com:389
uaa/ldap/credentials_identity: uid=servicebind,ou=Users,o=5c390cd9c556772e64d4fbb5,dc=jumpcloud,dc=com
uaa/ldap/credentials_password: ((uaa_ldap_password))
uaa/ldap/search_base: ou=Users,o=5c390cd9c556772e64d4fbb5,dc=jumpcloud,dc=com
uaa/ldap/search_filter: (&(objectClass=inetOrgPerson)(uid={0}))
uaa/ldap/group_search_base: ou=Users,o=5c390cd9c556772e64d4fbb5,dc=jumpcloud,dc=com
uaa/ldap/group_search_filter: member={0}
uaa/ldap/first_name_attribute: givenName
uaa/ldap/last_name_attribute: sn
uaa/ldap/mail_attribute_name: mail
uaa/ldap/external_groups_whitelist: pks_*

network_name: deployment

security_acknowledgement: X
singleton_availability_zone: az1
ha_proxy/skip_cert_verify: true
