vsphere_datastore: datastore1
vsphere_datacenter: Datacenter
infrastructure_network: "VM Network"
infrastructure_gateway: 192.168.7.1
dns: 192.168.7.1
ntp: time.nist.gov
vsphere_vms_folder: dev-pcf_vms
